properties:
       configuration:
         ingress:
           external: true
           targetPort: 80
           transport: http
         secrets:
           - name: azure-storage-connection-string
             value: null # Value set in Azure portal
       template:
         containers:
           - image: besspressregistry-dhapfpf0bqh9cjbu.azurecr.io/besspresspportalapi:latest
             name: besspresspportalapi
             env:
               - name: ASPNETCORE_URLS
                 value: "http://+:80"
               - name: AzureStorage__TableConnectionString
                 secretRef: azure-storage-connection-string
