properties:
  configuration:
    ingress:
      external: true
      targetPort: 80
      transport: http
  template:
    containers:
      - image: besspressregistry-dhapfpf0bqh9cjbu.azurecr.io/besspresspportalapi:latest
        name: besspresspportalapi
        env:
          - name: ASPNETCORE_URLS
            value: "http://+:80"
          - name: AzureStorage__ConnectionString
            value: "a070a176-c72c-473e-9766-69c19e94034a"
