name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

env:
  AZURE_CONTAINER_REGISTRY: besspressregistry-dhapfpf0bqh9cjbu.azurecr.io
  CONTAINER_APP_NAME_API: besspresspportalapi
  CONTAINER_APP_NAME_CLIENT: besspressportalclient
  RESOURCE_GROUP: BessPress
  LOCATION: westus2

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push API image
        run: |
          docker build -t $AZURE_CONTAINER_REGISTRY/$CONTAINER_APP_NAME_API:latest -f BessPressPortal.Api/Dockerfile .
          az acr login --name besspressregistry-dhapfpf0bqh9cjbu
          docker push $AZURE_CONTAINER_REGISTRY/$CONTAINER_APP_NAME_API:latest

      - name: Build and push Client image
        run: |
          docker build -t $AZURE_CONTAINER_REGISTRY/$CONTAINER_APP_NAME_CLIENT:latest -f BessPressPortal.Client/Dockerfile .
          az acr login --name besspressregistry-dhapfpf0bqh9cjbu
          docker push $AZURE_CONTAINER_REGISTRY/$CONTAINER_APP_NAME_CLIENT:latest

      - name: Deploy to Container App (API)
        run: |
          az containerapp update \
            --name $CONTAINER_APP_NAME_API \
            --resource-group $RESOURCE_GROUP \
            --yaml api-config.yaml

      - name: Deploy to Container App (Client)
        run: |
          az containerapp update \
            --name $CONTAINER_APP_NAME_CLIENT \
            --resource-group $RESOURCE_GROUP \
            --yaml client-config.yaml
