name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main  # or your default branch

env:
  AZURE_CONTAINER_REGISTRY: besspressregistry.azurecr.io
  CONTAINER_APP_NAME_API: besspresspportalapi
  CONTAINER_APP_NAME_CLIENT: besspressportalclient
  RESOURCE_GROUP: BessPress
  LOCATION: westus2

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push API image
        run: |
          docker build -t $AZURE_CONTAINER_REGISTRY/$CONTAINER_APP_NAME_API:latest -f BessPressPortal.Api/Dockerfile .
          echo "${{ secrets.AZURE_CREDENTIALS }}" | jq -r .clientSecret | docker login $AZURE_CONTAINER_REGISTRY -u ${{ secrets.AZURE_CLIENT_ID }} --password-stdin
          docker push $AZURE_CONTAINER_REGISTRY/$CONTAINER_APP_NAME_API:latest

      - name: Build and push Client image
        run: |
          docker build -t $AZURE_CONTAINER_REGISTRY/$CONTAINER_APP_NAME_CLIENT:latest -f BessPressPortal.Client/Dockerfile .
          docker push $AZURE_CONTAINER_REGISTRY/$CONTAINER_APP_NAME_CLIENT:latest

      - name: Deploy to Container App (API)
        run: |
          az containerapp update \
            --name $CONTAINER_APP_NAME_API \
            --resource-group $RESOURCE_GROUP \
            --image $AZURE_CONTAINER_REGISTRY/$CONTAINER_APP_NAME_API:latest

      - name: Deploy to Container App (Client)
        run: |
          az containerapp update \
            --name $CONTAINER_APP_NAME_CLIENT \
            --resource-group $RESOURCE_GROUP \
            --image $AZURE_CONTAINER_REGISTRY/$CONTAINER_APP_NAME_CLIENT:latest
